version: '2'

services:
    nginx:
        image: nginx
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d
            - ./yourProject/:/var/www/html
            - ./logs/nginx:/var/logs/nginx
        ports:
            - "8080:80"
        links:
            - php-fpm
            - mysql

    php-fpm:
        build: docker/php-fpm
        expose:
            - "9000"
        links:
            - mysql
        volumes:
            - ./yourProject:/var/www/html

    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: 123456