version: '2'

services:
    nginx:
        image: nginx
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d
            - ./yourProject/:/var/www/html
            - ./logs/nginx:/var/logs/nginx
        ports:
            - "8090:80"
        links:
            - php-fpm
            - mysql

    php-fpm:
        build: docker/php-fpm
        expose:
            - "9000"
        links:
            - mysql
        volumes:
            - ./yourProject:/var/www/html

    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASES=test
            - MYSQL_USER=root
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=123456
            - LANG=C.UTF-8
       volumes:
            - "./data/mysql:/var/lib/mysql"     
