FROM php:7.1-fpm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        libmemcached-dev \
        libz-dev \
        libpq-dev \
        libjpeg-dev \
        libpng12-dev \
        libfreetype6-dev \
        libssl-dev \
        libmcrypt-dev \
        libicu-dev \
        git \
        pkg-config \
        vim


RUN docker-php-ext-install iconv mcrypt mysqli pdo_mysql \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd bcmath intl zip opcache  \
#    && pecl install imagick \
#    && docker-php-ext-enable imagick \
    && pecl install apcu \
    && docker-php-ext-enable apcu

ADD ./php.ini /usr/local/etc/php/conf.d

CMD ["php-fpm"]

EXPOSE 9000